name: Rust

on:
  push:
    branches: [ "main", 'ci' ]
    
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-12
    
    if: "contains(github.event.head_commit.message, '[build]')"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Print cargo info
      run: cargo -vV
      
    - name: Install cross crate
      run: cargo install cross
      
    - name: Build
      run: cargo build --release --target aarch64-apple-darwin
